accent = "#9d7cd8"
cursor = "#eeeeee"
foreground = "#eeeeee"
background = "#000000"
selection_foreground = "#eeeeee"
selection_background = "#404040"

color0 = "#000000"
color1 = "#e06c75"
color2 = "#7fd88f"
color3 = "#e5c07b"
color4 = "#5c9cf5"
color5 = "#9d7cd8"
color6 = "#56b6c2"
color7 = "#ffffff"
color8 = "#808080"
color9 = "#e06c75"
color10 = "#7fd88f"
color11 = "#e5c07b"
color12 = "#5c9cf5"
color13 = "#9d7cd8"
color14 = "#56b6c2"
color15 = "#ffffff"
