# Madness Black
# Author: foliea

palette = 0=#000000
palette = 8=#808080

palette = 1=#e06c75
palette = 9=#e06c75

palette = 2=#7fd88f
palette = 10=#7fd88f

palette = 3=#e5c07b
palette = 11=#e5c07b

palette = 4=#5c9cf5
palette = 12=#5c9cf5

palette = 5=#9d7cd8
palette = 13=#9d7cd8

palette = 6=#56b6c2
palette = 14=#56b6c2

palette = 7=#ffffff
palette = 15=#ffffff

foreground = #eeeeee
background = #000000

selection-background = #404040
selection-foreground = #eeeeee

cursor-color = #eeeeee
cursor-text = #000000
