# Madness Black
# Author: foliea

# Palette
color0                   #000000
color8                   #808080

color1                   #e06c75
color9                   #e06c75

color2                   #7fd88f
color10                  #7fd88f

color3                   #e5c07b
color11                  #e5c07b

color4                   #5c9cf5
color12                  #5c9cf5

color5                   #9d7cd8
color13                  #9d7cd8

color6                   #56b6c2
color14                  #56b6c2

color7                   #ffffff
color15                  #ffffff

# Core
foreground               #eeeeee
background               #000000

# Selection
selection_background     #404040
selection_foreground     #eeeeee

# Cursor
cursor                   #eeeeee
cursor_text_color        #000000

# Borders
active_border_color      #9d7cd8
inactive_border_color    #808080

# Tabs
active_tab_foreground    #000000
active_tab_background    #9d7cd8
inactive_tab_foreground  #808080
inactive_tab_background  #0d0d0d
